### ISSUE TITLE
Unable to capture Boca.gov.tw page properly 

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#572] opened 2017-09-04 18:19 UTC
http://www.boca.gov.tw/content.asp?CuItem=175

**Comment by Conjuror** [comment] 2017-09-05 09:05
We cannot reproduce on several device. @joechengla can you describe more about it?

**Comment by joechengla** [comment] 2017-09-12 03:12
let's try turning on zoom override?

**Comment by chianger** [comment] 2017-09-15 07:16
propose P2 but let's confirm with @joechengla

**Comment by Conjuror** [comment] 2017-09-20 06:49
Assign to @joechengla since he didn't response. :p

**Closed** 2021-01-22 14:40 UTC
Labels: LEGACY, archived
