### ISSUE TITLE
After extended use, Lite can start occupying quite some storage

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#2935] opened 2018-11-20 15:22 UTC
And clear cache isn't enough
Some random thoughts
1. give users more insights and control on the user storage data Lite is using (bookmarks, history...etc)
2. allow users to remove some user data that's old (e.g. keep the latest 2 weeks of data)

**Comment by chianger** [comment] 2018-11-21 06:55
turns out this is by design due to the favicon storage. moving this to feature backlog for future enhancement.

**Closed** 2021-01-22 14:36 UTC
Labels: LEGACY, archived
